---
title: "Final project"
author: "Chi Fang"
date: "2019?~3??21??"
output: html_document
---

```{r}
rm(list=ls()) 
```

```{r}
#library
library(pacman)
p_load(broom, leaflet, leaflet.extras, maps, rnaturalearth, RColorBrewer, 
       rio, readxl, rlang, rgdal, WDI, sp, sf, tibble, tidyverse, dplyr, data.table, 
       htmltools, htmlwidgets, ggplot2, ggthemes, gridExtra, zoo)
devtools::install_github("hrbrmstr/streamgraph")
library(streamgraph)
```

The data I retrieved is a relatively "dirty" excel files from SIPRI. Two tasks are completed in this script. First, I extracted the indicators I need for mapping. Second, the data have to match the shape file in order to be manipulated in the interactive map. The matching part is the very reason why I kept the not so clean format. 

```{r}
#Preparing function: converting characters into numerics and integers
convert_round <- function(x){
  as.integer(round(as.numeric(as.character(x))))
}
convert_integer <- function(x){
  as.numeric(as.character(x))
}

#sipri_mb : mb for military burden
sipri_mb <- read_excel("C:/Users/diplo/OneDrive/Documents/data/SIPRI-Milex-data-1949-2017-1.xlsx", sheet = 8) %>%
  as.tibble() 
sipri_mb <- sipri_mb[c(6:203), c(1, 7:32)] #keeping only the national figure
a <- c(7, 8, 13, 61, 62, 76, 79, 91, 92, 98, 105, 112, 124, 129, 130, 136, 138, 151, 159, 180, 196:203) #ivalid rows on the dataframe (regions and subregions)
sipri_mb <- sipri_mb[-(a-5), ] #substracting the unwanted rows
colnames(sipri_mb) <- sipri_mb[c(1), ] #rename the column name by the first row
sipri_mb <- sipri_mb[-c(1), ] %>%
  as.data.frame() %>%
  write.csv("military_burden.csv")%>%
  print() 
```
```{r}
#military expenditure as the share of gdp
sipri_gdp <- read_excel("C:/Users/diplo/OneDrive/Documents/data/SIPRI-Milex-data-1949-2017-1.xlsx", sheet = 7) %>%
  as.tibble() 
sipri_gdp <- sipri_gdp[c(5:196), c(1, 46:71)]
sipri_gdp
b <- c(6, 7, 12, 60, 61, 75, 78, 90, 91, 97, 104, 111, 123, 128, 129, 135, 137, 149, 150, 158, 159, 180) #ivalid rows on the dataframe (regions and subregions)
sipri_gdp <- sipri_gdp[-(b-4), ] #substracting the unwanted rows
colnames(sipri_gdp) <- sipri_gdp[c(1), ] #rename the column name by the first row
sipri_gdp <- sipri_gdp[-c(1), ] %>%
  as.data.frame() %>%
  write.csv("military_gdp_share.csv")%>%
  print() 
```
```{r}
#military expenditure in terms of us current
sipri_exp <- read_excel("C:/Users/diplo/OneDrive/Documents/data/SIPRI-Milex-data-1949-2017-1.xlsx", sheet = 6) %>%
  as.tibble() 
sipri_exp <- sipri_exp[c(5:196), c(1, 46:71)]
sipri_exp <- sipri_exp[-(b-4), ] #substracting the unwanted rows
colnames(sipri_exp) <- sipri_exp[c(1), ] #rename the column name by the first row
sipri_exp <- sipri_exp[-c(1), ]  %>%
  as.data.frame() %>% 
  write.csv("military_expense.csv")%>%
  print()
```

```{r}
#iso alpha code 
iso <- read.csv("C:/Users/diplo/OneDrive/Documents/data/countries_codes_and_coordinates.csv") %>%
  as.data.frame()
#load the shape file
countries <- ne_countries(scale = 'large')
files <- c(sipri_mb, sipri_gdp, sipri_exp)
#Combine iso alpha code with the datasets (for further integrating with the shape file)
sipri_mb <- left_join(x = sipri_mb,
                      y = iso,
                      by = c("Country" = "Country")) 
sipri_gdp <- left_join(x = sipri_gdp,
                       y = iso,
                       by = c("Country" = "Country")) 
sipri_exp <- left_join(x = sipri_exp,
                       y = iso,
                       by = c("Country" = "Country")) 
#Combine sipri dataset with the world shape file
countries@data = data.frame(countries@data,
                            sipri_mb[
                              match(countries@data[, "iso_a2"], 
                                          sipri_mb[, "Alpha.2code"]),
                              ]
                                  )
countries@data = data.frame(countries@data,
                            sipri_gdp[
                              match(countries@data[, "iso_a2"], 
                                          sipri_gdp[, "Alpha.2code"]),
                              ]
                                  )
countries@data = data.frame(countries@data,
                            sipri_exp[
                              match(countries@data[, "iso_a2"], 
                                          sipri_exp[, "Alpha.2code"]),
                              ]
                                  )
#Selecting columns
var_col <- c(96:121, 160:185)
var_col1 <- c(128:153)
for(x in var_col){
  countries@data[, x] <- convert_round(countries@data[, x])
}
for(x in var_col1){
  countries@data[, x] <- convert_integer(countries@data[, x])
}
write.csv(countries@data, "mapping_data.csv")
```





